package ru.yakaska.mireadaimyo.ui.theme

import androidx.compose.ui.graphics.Color

val daimyoLightPrimary = Color(0xFF825500)
val daimyoLightOnPrimary = Color(0xFFFFFFFF)
val daimyoLightPrimaryContainer = Color(0xFFFFDDAE)
val daimyoLightOnPrimaryContainer = Color(0xFF2A1800)
val daimyoLightSecondary = Color(0xFF6F5B40)
val daimyoLightOnSecondary = Color(0xFFFFFFFF)
val daimyoLightSecondaryContainer = Color(0xFFFADEBC)
val daimyoLightOnSecondaryContainer = Color(0xFF271904)
val daimyoLightTertiary = Color(0xFF516440)
val daimyoLightOnTertiary = Color(0xFFFFFFFF)
val daimyoLightTertiaryContainer = Color(0xFFD3EABC)
val daimyoLightOnTertiaryContainer = Color(0xFF102004)
val daimyoLightError = Color(0xFFBA1B1B)
val daimyoLightErrorContainer = Color(0xFFFFDAD4)
val daimyoLightOnError = Color(0xFFFFFFFF)
val daimyoLightOnErrorContainer = Color(0xFF410001)
val daimyoLightBackground = Color(0xFFFCFCFC)
val daimyoLightOnBackground = Color(0xFF1F1B16)
val daimyoLightSurface = Color(0xFFFCFCFC)
val daimyoLightOnSurface = Color(0xFF1F1B16)
val daimyoLightSurfaceVariant = Color(0xFFF0E0CF)
val daimyoLightOnSurfaceVariant = Color(0xFF4F4539)
val daimyoLightOutline = Color(0xFF817567)
val daimyoLightInverseOnSurface = Color(0xFFF9EFE6)
val daimyoLightInverseSurface = Color(0xFF34302A)
val daimyoLightPrimaryInverse = Color(0xFFFFB945)

val daimyoDarkPrimary = Color(0xFFFFB945)
val daimyoDarkOnPrimary = Color(0xFF452B00)
val daimyoDarkPrimaryContainer = Color(0xFF624000)
val daimyoDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val daimyoDarkSecondary = Color(0xFFDDC3A2)
val daimyoDarkOnSecondary = Color(0xFF3E2E16)
val daimyoDarkSecondaryContainer = Color(0xFF56442B)
val daimyoDarkOnSecondaryContainer = Color(0xFFFADEBC)
val daimyoDarkTertiary = Color(0xFFB8CEA2)
val daimyoDarkOnTertiary = Color(0xFF243516)
val daimyoDarkTertiaryContainer = Color(0xFF3A4C2B)
val daimyoDarkOnTertiaryContainer = Color(0xFFD3EABC)
val daimyoDarkError = Color(0xFFFFB4A9)
val daimyoDarkErrorContainer = Color(0xFF930006)
val daimyoDarkOnError = Color(0xFF680003)
val daimyoDarkOnErrorContainer = Color(0xFFFFDAD4)
val daimyoDarkBackground = Color(0xFF1F1B16)
val daimyoDarkOnBackground = Color(0xFFEAE1D9)
val daimyoDarkSurface = Color(0xFF1F1B16)
val daimyoDarkOnSurface = Color(0xFFEAE1D9)
val daimyoDarkSurfaceVariant = Color(0xFF4F4539)
val daimyoDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val daimyoDarkOutline = Color(0xFF9C8F80)
val daimyoDarkInverseOnSurface = Color(0xFF32281A)
val daimyoDarkInverseSurface = Color(0xFFEAE1D9)
val daimyoDarkPrimaryInverse = Color(0xFF624000)